# CCH objects are deliberately kept as plain R lists. They can be saved with
# saveRDS() and reused later, which is important for traffic assignment models
# that run many congestion iterations on the same road topology.

cch_topology_fields <- function(){
  c("rank", "tail", "head", "first_out", "adj_head", "adj_arc",
    "rank_first_out", "rank_adj_head", "rank_adj_arc",
    "input_arc", "input_forward", "elimination_tree_parent")
}

validate_cch_for_graph <- function(cch, Graph){
  if (!inherits(cch, "cppRouting_cch")) stop("cch must be generated by cpp_cch_prepare()")
  if (cch$nbnode != Graph$nbnode) stop("cch was prepared for a graph with a different number of nodes")
  if (nrow(cch$original$data) != nrow(Graph$data)) stop("cch was prepared for a graph with a different number of edges")
  if (!all(cch$original$data$from == Graph$data$from) || !all(cch$original$data$to == Graph$data$to)) {
    stop("cch must be prepared from the same graph topology")
  }

  missing_fields <- setdiff(cch_topology_fields(), names(cch))
  if (length(missing_fields) > 0) {
    stop("cch was prepared with an older CCH format. Regenerate it with cpp_cch_prepare().")
  }

  TRUE
}

#' Prepare a customizable contraction hierarchy
#'
#' @description
#' Build the part of a customizable contraction hierarchy (CCH) that depends
#' only on the graph topology. This is the expensive step that should be done
#' once, saved with \code{saveRDS()} if needed, then reused when edge costs
#' change.
#'
#' @param Graph An object generated by \link{makegraph}.
#' @param order Optional node order. Values must be node references from
#' \code{Graph$dict$ref}. If omitted, cppRouting computes a simple local order.
#' Large road networks usually benefit from a stronger nested-dissection order
#' prepared outside this helper.
#' @return A CCH topology object. Run \link{cpp_cch_customize} before distance
#' queries, or pass it to \link{assign_traffic} through the \code{cch} argument
#' to avoid rebuilding the topology at each model run.
#' @details
#' CCH separates routing into two phases:
#' \itemize{
#'   \item \strong{Preparation}: builds shortcuts from the road topology. This
#'   step is reusable as long as the set of edges does not change.
#'   \item \strong{Customization}: updates shortcut costs from the current edge
#'   weights. This step is repeated when congestion changes travel times.
#' }
#'
#' For traffic assignment, prepare once and call \code{assign_traffic(...,
#' aon_method = "cch", cch = cch)}. The CCH assignment path uses the
#' elimination-tree query, which is the fast query variant for repeated origins
#' or repeated destinations.
#' @examples
#' RcppParallel::setThreadOptions(numThreads = 1)
#'
#' edges <- data.frame(from_vertex = c(0, 0, 1, 1, 2),
#'                     to_vertex = c(1, 2, 2, 3, 3),
#'                     cost = c(1, 4, 1, 2, 1))
#' graph <- makegraph(edges, directed = TRUE)
#'
#' cch <- cpp_cch_prepare(graph)
#' metric <- cpp_cch_customize(cch)
#' get_distance_pair(metric, from = c(0, 1), to = c(3, 3))
#' @export
cpp_cch_prepare <- function(Graph, order = NULL){
  if (length(Graph) != 5) stop("Input should be generated by makegraph()")

  if (is.null(order)){
    order_id <- integer(0)
  } else {
    order <- as.character(order)
    if (length(order) != Graph$nbnode) stop("order must contain one entry for each node")
    if (sum(order %in% Graph$dict$ref) < length(order)) stop("Some order nodes are not in the graph")
    if (any(duplicated(order))) stop("order contains duplicated nodes")
    order_id <- Graph$dict$id[match(order, Graph$dict$ref)]
  }

  cch <- cppcchprepare(Graph$data$from, Graph$data$to, Graph$nbnode, order_id)

  cch$nbnode <- Graph$nbnode
  cch$dict <- Graph$dict
  cch$original <- Graph[c("data", "attrib")]
  structure(cch,
            class = "cppRouting_cch")
}

#' Customize a CCH with edge weights
#'
#' @description
#' Update a prepared CCH with the edge weights that should be used for shortest
#' path queries. Customization is much cheaper than preparing the CCH topology,
#' so it is the step to repeat when congestion changes travel times.
#'
#' @param CCH An object generated by \link{cpp_cch_prepare}.
#' @param weights Optional edge weights. Defaults to the original graph cost.
#' @return A customized CCH metric object usable by \link{get_distance_pair},
#' \link{get_distance_matrix}, \link{get_path_values_pair}, and \link{get_aon}.
#' @details
#' The \code{weights} vector must follow the same edge order as
#' \code{CCH$original$data}. In a traffic model this is normally the current
#' congested travel time for every edge.
#' @references Dibbelt, J., Strasser, B., and Wagner, D. (2016).
#' "Customizable Contraction Hierarchies". ACM Journal of Experimental
#' Algorithmics, 21, Article 1.5. \doi{10.1145/2886843}.
#' @export
cpp_cch_customize <- function(CCH, weights = NULL){
  if (!inherits(CCH, "cppRouting_cch")) stop("Input should be generated by cpp_cch_prepare()")
  if (length(setdiff(cch_topology_fields(), names(CCH))) > 0) {
    stop("CCH was prepared with an older CCH format. Regenerate it with cpp_cch_prepare().")
  }

  if (is.null(weights)) weights <- CCH$original$data$dist
  weights <- as.numeric(weights)
  if (length(weights) != nrow(CCH$original$data)) stop("weights must have one value per original edge")
  if (any(is.na(weights))) stop("NAs are not allowed in weights")
  if (any(weights < 0)) stop("Negative weights are not allowed")

  metric <- cppcchcustomize(CCH$original$data$from,
                            CCH$original$data$to,
                            weights,
                            CCH$nbnode,
                            CCH$rank,
                            CCH$tail,
                            CCH$head,
                            CCH$rank_first_out,
                            CCH$rank_adj_head,
                            CCH$rank_adj_arc,
                            CCH$input_arc,
                            CCH$input_forward)

  CCH$weight <- metric
  CCH$weights <- weights
  structure(CCH,
            class = "cppRouting_cch_metric")
}
