#' Accumulate edge values along shortest paths
#'
#' @description
#' Compute shortest paths and sum one or more edge value columns along each
#' selected path.
#'
#' @param Graph A customized CCH metric generated by \link{cpp_cch_customize},
#' or a contracted CH graph generated by \link{cpp_contract}.
#' @param from A vector of origin vertices.
#' @param to A vector of destination vertices.
#' @param values Numeric vector, matrix, data.frame or named list with one row
#' per original graph edge. Each column is summed along the shortest path.
#' @return A data.frame with \code{from}, \code{to}, routing \code{cost}, and
#' one column for each supplied value.
#' @details
#' The shortest path is chosen with the routing cost stored in \code{Graph}.
#' The \code{values} columns do not affect routing; they are accumulated along
#' the original graph edges used by the selected path.
#'
#' This is useful when travel time is the routing cost but a model also needs
#' distance, real time, or other edge attributes along the same path.
#' @examples
#' RcppParallel::setThreadOptions(numThreads = 1)
#'
#' edges <- data.frame(from_vertex = c(0, 0, 1, 1, 2),
#'                     to_vertex = c(1, 2, 2, 3, 3),
#'                     time = c(1, 4, 1, 2, 1),
#'                     distance = c(10, 30, 10, 20, 10))
#' graph <- makegraph(edges[, 1:3], directed = TRUE)
#'
#' cch <- cpp_cch_prepare(graph)
#' metric <- cpp_cch_customize(cch)
#' get_path_values_pair(metric, from = c(0, 0), to = c(3, 2),
#'                      values = data.frame(distance = edges$distance))
#'
#' ch <- cpp_contract(graph)
#' get_path_values_pair(ch, from = c(0, 0), to = c(3, 2),
#'                      values = data.frame(distance = edges$distance))
#' @export
get_path_values_pair <- function(Graph, from, to, values){
  if (inherits(Graph, "cppRouting_cch")) stop("Run cpp_cch_customize() before querying a CCH")
  if (!inherits(Graph, "cppRouting_cch_metric") && length(Graph) != 6) {
    stop("Graph must be a CCH metric generated by cpp_cch_customize() or a contracted graph generated by cpp_contract()")
  }
  if (length(from) != length(to)) stop("From and to have not the same length")
  if (any(is.na(cbind(from, to)))) stop("NAs are not allowed in origin/destination nodes")

  from <- as.character(from)
  to <- as.character(to)
  allnodes <- c(from, to)
  if (sum(allnodes %in% Graph$dict$ref) < length(allnodes)) stop("Some nodes are not in the graph")

  values <- normalize_path_values(values)

  if (nrow(values$data) != nrow(Graph$original$data)) stop("values must have one row per original edge")

  from_id <- Graph$dict$id[match(from, Graph$dict$ref)]
  to_id <- Graph$dict$id[match(to, Graph$dict$ref)]

  if (length(Graph) == 6) {
    result <- path_values_pair_ch(Graph, from_id, to_id, values$data)
    colnames(result) <- c("cost", values$names)
    return(data.frame(from = from, to = to, result, check.names = FALSE))
  }

  result <- cpppathvaluescch(Graph$original$data$from,
                             Graph$nbnode,
                             Graph$rank,
                             Graph$first_out,
                             Graph$adj_head,
                             Graph$adj_arc,
                             Graph$elimination_tree_parent,
                             Graph$weight$forward,
                             Graph$weight$backward,
                             Graph$weight$forward_first_arc,
                             Graph$weight$forward_first_dir,
                             Graph$weight$forward_second_arc,
                             Graph$weight$forward_second_dir,
                             Graph$weight$forward_original,
                             Graph$weight$backward_first_arc,
                             Graph$weight$backward_first_dir,
                             Graph$weight$backward_second_arc,
                             Graph$weight$backward_second_dir,
                             Graph$weight$backward_original,
                             from_id,
                             to_id,
                             values$data)
  colnames(result) <- c("cost", values$names)
  data.frame(from = from, to = to, result, check.names = FALSE)
}

normalize_path_values <- function(values) {
  if (is.null(values)) stop("values must contain at least one edge value column")

  if (is.data.frame(values)) {
    if (!all(vapply(values, is.numeric, logical(1)))) stop("all values columns must be numeric")
    value_names <- names(values)
    values <- as.matrix(values)
  } else if (is.list(values) && !is.data.frame(values)) {
    if (!all(vapply(values, is.numeric, logical(1)))) stop("all values columns must be numeric")
    values <- as.data.frame(values)
    value_names <- names(values)
    values <- as.matrix(values)
  } else {
    if (!is.numeric(values)) stop("values must be numeric")
    values <- as.matrix(values)
    value_names <- colnames(values)
  }

  storage.mode(values) <- "double"
  if (ncol(values) == 0) stop("values must contain at least one edge value column")
  if (any(is.na(values))) stop("NAs are not allowed in values")

  if (is.null(value_names)) value_names <- paste0("value", seq_len(ncol(values)))
  missing_names <- is.na(value_names) | value_names == ""
  value_names[missing_names] <- paste0("value", which(missing_names))

  list(data = values, names = value_names)
}

path_values_pair_ch <- function(Graph, from_id, to_id, values) {
  cpppathvaluesC(
    Graph$original$data$from,
    Graph$original$data$to,
    Graph$original$data$dist,
    values,
    Graph$data$from,
    Graph$data$to,
    Graph$data$dist,
    Graph$nbnode,
    Graph$rank,
    Graph$shortcuts$shortf,
    Graph$shortcuts$shortt,
    Graph$shortcuts$shortc,
    FALSE,
    from_id,
    to_id
  )
}
