#' Accumulate edge values along CCH shortest paths
#'
#' @description
#' Compute shortest paths with a customized CCH metric and sum one or more edge
#' value columns along each selected path.
#'
#' @param Graph A customized CCH metric generated by \link{cpp_cch_customize}.
#' @param from A vector of origin vertices.
#' @param to A vector of destination vertices.
#' @param values Numeric vector, matrix, data.frame or named list with one row
#' per original graph edge. Each column is summed along the shortest path.
#' @return A data.frame with \code{from}, \code{to}, routing \code{cost}, and
#' one column for each supplied value.
#' @details
#' The shortest path is chosen with the CCH routing cost stored in \code{Graph}.
#' The \code{values} columns do not affect routing; they are only accumulated
#' after the path has been recovered and unpacked to original graph edges.
#'
#' This is useful when travel time is the routing cost but a model also needs
#' distance, real time, or other edge attributes along the same path.
#' @examples
#' RcppParallel::setThreadOptions(numThreads = 1)
#'
#' edges <- data.frame(from_vertex = c(0, 0, 1, 1, 2),
#'                     to_vertex = c(1, 2, 2, 3, 3),
#'                     time = c(1, 4, 1, 2, 1),
#'                     distance = c(10, 30, 10, 20, 10))
#' graph <- makegraph(edges[, 1:3], directed = TRUE)
#'
#' cch <- cpp_cch_prepare(graph)
#' metric <- cpp_cch_customize(cch)
#' get_path_values_pair(metric, from = c(0, 0), to = c(3, 2),
#'                      values = data.frame(distance = edges$distance))
#' @export
get_path_values_pair <- function(Graph, from, to, values){
  if (!inherits(Graph, "cppRouting_cch_metric")) stop("Graph must be generated by cpp_cch_customize()")
  if (length(from) != length(to)) stop("From and to have not the same length")
  if (any(is.na(cbind(from, to)))) stop("NAs are not allowed in origin/destination nodes")

  from <- as.character(from)
  to <- as.character(to)
  allnodes <- c(from, to)
  if (sum(allnodes %in% Graph$dict$ref) < length(allnodes)) stop("Some nodes are not in the graph")

  if (is.null(values)) stop("values must contain at least one edge value column")
  if (is.data.frame(values) || is.list(values)) {
    values <- as.data.frame(values)
    value_names <- names(values)
    values <- as.matrix(values)
  } else {
    values <- as.matrix(values)
    value_names <- colnames(values)
  }

  storage.mode(values) <- "double"
  if (ncol(values) == 0) stop("values must contain at least one edge value column")
  if (nrow(values) != nrow(Graph$original$data)) stop("values must have one row per original edge")
  if (any(is.na(values))) stop("NAs are not allowed in values")

  if (is.null(value_names)) value_names <- paste0("value", seq_len(ncol(values)))
  missing_names <- is.na(value_names) | value_names == ""
  value_names[missing_names] <- paste0("value", which(missing_names))

  from_id <- Graph$dict$id[match(from, Graph$dict$ref)]
  to_id <- Graph$dict$id[match(to, Graph$dict$ref)]

  result <- cpppathvaluescch(Graph$original$data$from,
                             Graph$nbnode,
                             Graph$rank,
                             Graph$first_out,
                             Graph$adj_head,
                             Graph$adj_arc,
                             Graph$elimination_tree_parent,
                             Graph$weight$forward,
                             Graph$weight$backward,
                             Graph$weight$forward_first_arc,
                             Graph$weight$forward_first_dir,
                             Graph$weight$forward_second_arc,
                             Graph$weight$forward_second_dir,
                             Graph$weight$forward_original,
                             Graph$weight$backward_first_arc,
                             Graph$weight$backward_first_dir,
                             Graph$weight$backward_second_arc,
                             Graph$weight$backward_second_dir,
                             Graph$weight$backward_original,
                             from_id,
                             to_id,
                             values)
  colnames(result) <- c("cost", value_names)
  data.frame(from = from, to = to, result, check.names = FALSE)
}
